"""added desc in tags

Revision ID: 27994486e9c2
Revises: d4c82f14b258
Create Date: 2025-07-23 21:17:21.343277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27994486e9c2'
down_revision = 'd4c82f14b258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
